# Generated by Django 5.2.7 on 2025-10-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_paymentgateway_invoice_overduecharge_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='usd', max_length=8),
        ),
    ]
