# Generated by Django 5.2.7 on 2025-10-23 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_invoice_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_financial_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('activa', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_card_id', models.CharField(max_length=255)),
                ('stripe_cardholder_id', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('virtual', 'Virtual'), ('physical', 'Física')], default='virtual', max_length=20)),
                ('ultimos_digitos', models.CharField(blank=True, max_length=4, null=True)),
                ('estado', models.CharField(choices=[('active', 'Activa'), ('inactive', 'Inactiva'), ('canceled', 'Cancelada'), ('lost', 'Perdida'), ('stolen', 'Robada')], default='active', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cuenta_financiera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='finanzas.cuentafinanciera')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_transaction_id', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('deposit', 'Depósito'), ('withdrawal', 'Retiro'), ('transfer_in', 'Transferencia entrante'), ('transfer_out', 'Transferencia saliente'), ('card_payment', 'Pago con tarjeta')], max_length=20)),
                ('monto', models.IntegerField()),
                ('moneda', models.CharField(default='usd', max_length=3)),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('succeeded', 'Completada'), ('failed', 'Fallida'), ('canceled', 'Cancelada')], default='pending', max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cuenta_financiera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='finanzas.cuentafinanciera')),
                ('tarjeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.tarjeta')),
            ],
        ),
    ]
