# Generated by Django 5.2.6 on 2025-10-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_cuentafinanciera_tarjeta_transaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='last_error',
            field=models.TextField(blank=True, help_text='Último error ocurrido al procesar este webhook (si aplica)', null=True),
        ),
    ]
