# Generated by Django 5.2.6 on 2025-10-23 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0009_compliancelog_payment_support_ticket_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='expiry_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='expiry_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CurrencyConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_amount', models.BigIntegerField()),
                ('original_currency', models.CharField(max_length=8)),
                ('converted_amount', models.BigIntegerField()),
                ('target_currency', models.CharField(max_length=8)),
                ('exchange_rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('conversion_timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='finanzas.payment')),
            ],
        ),
    ]
