# Generated by Django 5.2.6 on 2025-10-04 20:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('id_acceso', models.AutoField(help_text='ID único del acceso', primary_key=True, serialize=False)),
                ('hora_entrada', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Hora de entrada')),
                ('hora_salida', models.DateTimeField(blank=True, help_text='Hora de salida', null=True)),
                ('lugar', models.CharField(help_text='Lugar del acceso (entrada principal, garaje, etc.)', max_length=100)),
                ('metodo', models.CharField(choices=[('biometria', 'Biometría'), ('qr', 'Código QR'), ('rfid', 'RFID'), ('pin', 'PIN'), ('manual', 'Manual')], help_text='Método utilizado para el acceso', max_length=50)),
                ('resultado', models.CharField(choices=[('exitoso', 'Exitoso'), ('denegado', 'Denegado'), ('error', 'Error')], db_index=True, help_text='Resultado del intento de acceso', max_length=50)),
                ('motivo', models.CharField(blank=True, help_text='Motivo del acceso o denegación', max_length=100)),
            ],
            options={
                'verbose_name': 'Acceso',
                'verbose_name_plural': 'Accesos',
                'db_table': 'acceso',
                'ordering': ['-hora_entrada'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(help_text='ID único de la persona', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_index=True, help_text='Nombre de la persona', max_length=50)),
                ('apellido', models.CharField(db_index=True, help_text='Apellido de la persona', max_length=50)),
                ('ci', models.IntegerField(db_index=True, help_text='Cédula de identidad (número entero)', unique=True, validators=[django.core.validators.MinValueValidator(100000, message='CI debe tener al menos 6 dígitos'), django.core.validators.MaxValueValidator(999999999999, message='CI no puede tener más de 12 dígitos')])),
                ('email', models.EmailField(db_index=True, help_text='Correo electrónico único', max_length=100, unique=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], help_text='Sexo de la persona', max_length=20, null=True)),
                ('telefono', models.IntegerField(blank=True, db_index=True, help_text='Número de teléfono (sin espacios ni caracteres especiales)', null=True, validators=[django.core.validators.MinValueValidator(1000000, message='Teléfono debe tener al menos 7 dígitos'), django.core.validators.MaxValueValidator(999999999999999, message='Teléfono no puede tener más de 15 dígitos')])),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='Fecha de nacimiento', null=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'persona',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='AreaComun',
            fields=[
                ('id_areacomun', models.AutoField(help_text='ID único del área común', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_index=True, help_text='Nombre del área común', max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('salon_eventos', 'Salón de Eventos'), ('gimnasio', 'Gimnasio'), ('piscina', 'Piscina'), ('terraza', 'Terraza'), ('parrillero', 'Parrillero'), ('salon_usos_multiples', 'Salón de Usos Múltiples'), ('cancha_deportiva', 'Cancha Deportiva'), ('jardin', 'Jardín'), ('estacionamiento', 'Estacionamiento')], help_text='Tipo de área común', max_length=50)),
                ('piso', models.IntegerField(help_text='Piso donde se ubica el área común', validators=[django.core.validators.MinValueValidator(-5, message='El piso no puede ser menor a -5'), django.core.validators.MaxValueValidator(50, message='El piso no puede ser mayor a 50')])),
            ],
            options={
                'verbose_name': 'Área Común',
                'verbose_name_plural': 'Áreas Comunes',
                'db_table': 'area_comun',
                'ordering': ['piso', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, db_index=True, help_text='Username/CI del usuario (para casos donde se elimine el usuario)', max_length=150)),
                ('evento', models.CharField(choices=[('login_exitoso', 'Login exitoso'), ('login_fallido', 'Login fallido'), ('logout_exitoso', 'Logout exitoso'), ('cambio_password', 'Cambio de contraseña'), ('reset_password', 'Reset de contraseña'), ('acceso_no_autorizado', 'Acceso no autorizado'), ('acceso_biometrico', 'Acceso biométrico'), ('registro_usuario', 'Registro de usuario'), ('modificacion_perfil', 'Modificación de perfil'), ('eliminacion_cuenta', 'Eliminación de cuenta'), ('activacion_2fa', 'Activación 2FA'), ('desactivacion_2fa', 'Desactivación 2FA')], db_index=True, help_text='Tipo de evento registrado', max_length=32)),
                ('ip', models.GenericIPAddressField(blank=True, help_text='Dirección IP desde donde se realizó la acción', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Información del navegador/cliente')),
                ('fecha', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Fecha y hora del evento')),
                ('detalle', models.TextField(blank=True, help_text='Detalles adicionales del evento')),
            ],
            options={
                'verbose_name': 'Evento de Auditoría',
                'verbose_name_plural': 'Eventos de Auditoría',
                'db_table': 'auditoria_evento',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Biometricos',
            fields=[
                ('id_biometrico', models.AutoField(help_text='ID único del registro biométrico', primary_key=True, serialize=False)),
                ('huellas_encrypted', models.TextField(blank=True, help_text='Datos de huellas dactilares encriptados', null=True)),
                ('rostro_encrypted', models.TextField(blank=True, help_text='Datos de reconocimiento facial encriptados', null=True)),
                ('iris_encrypted', models.TextField(blank=True, help_text='Datos de reconocimiento de iris encriptados', null=True)),
            ],
            options={
                'verbose_name': 'Dato Biométrico',
                'verbose_name_plural': 'Datos Biométricos',
                'db_table': 'biometricos',
            },
        ),
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('id_camara', models.AutoField(help_text='ID único de la cámara', primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(db_index=True, help_text='Ubicación de la cámara', max_length=100)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('mantenimiento', 'En Mantenimiento'), ('dañada', 'Dañada')], db_index=True, default='activa', help_text='Estado actual de la cámara', max_length=20)),
            ],
            options={
                'verbose_name': 'Cámara',
                'verbose_name_plural': 'Cámaras',
                'db_table': 'camara',
                'ordering': ['ubicacion'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(help_text='ID único del departamento', primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(db_index=True, help_text='Nombre o número del departamento (ej: 101, A-1)', max_length=50, unique=True)),
                ('piso', models.IntegerField(db_index=True, help_text='Número de piso donde se ubica', validators=[django.core.validators.MinValueValidator(-5, message='El piso no puede ser menor a -5'), django.core.validators.MaxValueValidator(50, message='El piso no puede ser mayor a 50')])),
                ('nro_habitaciones', models.IntegerField(help_text='Número de habitaciones', validators=[django.core.validators.MinValueValidator(0, message='Número de habitaciones no puede ser negativo'), django.core.validators.MaxValueValidator(20, message='Número de habitaciones no puede ser mayor a 20')])),
                ('nro_banios', models.IntegerField(help_text='Número de baños', validators=[django.core.validators.MinValueValidator(0, message='Número de baños no puede ser negativo'), django.core.validators.MaxValueValidator(10, message='Número de baños no puede ser mayor a 10')])),
                ('area', models.IntegerField(help_text='Área en metros cuadrados', validators=[django.core.validators.MinValueValidator(1, message='Área debe ser mayor a 0'), django.core.validators.MaxValueValidator(10000, message='Área no puede ser mayor a 10000 m²')])),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamento',
                'ordering': ['piso', 'nombre_departamento'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(help_text='ID único de la factura', primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre o descripción de la factura', max_length=100)),
                ('fecha_emision', models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Fecha de emisión de la factura')),
                ('fecha_vencimiento', models.DateField(db_index=True, help_text='Fecha de vencimiento de la factura')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la factura')),
                ('costo_total', models.DecimalField(decimal_places=2, help_text='Costo total de la factura', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], db_index=True, default='pendiente', help_text='Estado actual de la factura', max_length=20)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'factura',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='Grabacion',
            fields=[
                ('id_grabacion', models.AutoField(help_text='ID único de la grabación', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Fecha y hora de la grabación')),
                ('archivo', models.CharField(help_text='Ruta del archivo de grabación', max_length=255)),
            ],
            options={
                'verbose_name': 'Grabación',
                'verbose_name_plural': 'Grabaciones',
                'db_table': 'grabacion',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id_incidente', models.AutoField(help_text='ID único del incidente', primary_key=True, serialize=False)),
                ('descripcion', models.TextField(help_text='Descripción detallada del incidente')),
                ('fecha', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Fecha y hora del incidente')),
                ('tipo', models.CharField(choices=[('seguridad', 'Seguridad'), ('mantenimiento', 'Mantenimiento'), ('emergencia', 'Emergencia'), ('ruido', 'Ruido'), ('limpieza', 'Limpieza'), ('otros', 'Otros')], db_index=True, help_text='Tipo de incidente', max_length=50)),
                ('archivo', models.CharField(blank=True, help_text='Archivo adjunto (foto, video, documento)', max_length=255)),
                ('ubicacion', models.CharField(help_text='Ubicación donde ocurrió el incidente', max_length=100)),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
                'db_table': 'incidente',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id_mantenimiento', models.AutoField(help_text='ID único del mantenimiento', primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del trabajo de mantenimiento', max_length=100)),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('emergencia', 'Emergencia'), ('mejora', 'Mejora')], help_text='Tipo de mantenimiento', max_length=50)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del mantenimiento')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'db_table': 'mantenimiento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(help_text='ID único de la notificación', primary_key=True, serialize=False)),
                ('mensaje', models.TextField(help_text='Contenido del mensaje de la notificación')),
                ('fecha_envio', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Fecha y hora de envío')),
                ('motivo', models.CharField(help_text='Motivo o razón de la notificación', max_length=100)),
                ('via', models.CharField(choices=[('push', 'Push Notification'), ('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], help_text='Medio por el cual se envía la notificación', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('leida', 'Leída'), ('fallida', 'Fallida')], db_index=True, default='pendiente', help_text='Estado actual de la notificación', max_length=20)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificacion',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Notifican',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(help_text='Contenido de la notificación')),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de envío')),
                ('motivo', models.CharField(help_text='Motivo de la notificación', max_length=100)),
                ('via', models.CharField(choices=[('push', 'Push Notification'), ('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], help_text='Medio de envío', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('leida', 'Leída'), ('fallida', 'Fallida')], default='pendiente', help_text='Estado de la notificación', max_length=20)),
            ],
            options={
                'verbose_name': 'Notificación de Servicio',
                'verbose_name_plural': 'Notificaciones de Servicios',
                'db_table': 'notifican',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(help_text='ID único del pago', primary_key=True, serialize=False)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('cheque', 'Cheque'), ('tarjeta_debito', 'Tarjeta de Débito'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('qr', 'Código QR'), ('online', 'Pago Online')], help_text='Método utilizado para el pago', max_length=50)),
                ('fecha_pago', models.DateField(blank=True, db_index=True, help_text='Fecha en que se realizó el pago', null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('revertido', 'Revertido')], db_index=True, default='pendiente', help_text='Estado actual del pago', max_length=20)),
                ('referencia_bancaria_encrypted', models.TextField(blank=True, help_text='Referencia bancaria encriptada', null=True)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pago',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='Realiza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de realización')),
            ],
            options={
                'verbose_name': 'Asignación Mantenimiento',
                'verbose_name_plural': 'Asignaciones Mantenimiento',
                'db_table': 'realiza',
            },
        ),
        migrations.CreateModel(
            name='Reciben',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Usuario-Notificación',
                'verbose_name_plural': 'Usuarios-Notificaciones',
                'db_table': 'reciben',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(help_text='ID único de la reserva', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_index=True, help_text='Fecha de la reserva')),
                ('hora_inicio', models.TimeField(help_text='Hora de inicio de la reserva')),
                ('hora_fin', models.TimeField(help_text='Hora de fin de la reserva')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada'), ('no_show', 'No Show')], db_index=True, default='pendiente', help_text='Estado de la reserva', max_length=20)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reserva',
                'ordering': ['-fecha', '-hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Resuelve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('asignado', 'Asignado'), ('en_proceso', 'En Proceso'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='asignado', help_text='Estado de la resolución', max_length=20)),
            ],
            options={
                'verbose_name': 'Resolución de Incidente',
                'verbose_name_plural': 'Resoluciones de Incidentes',
                'db_table': 'resuelve',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(help_text='ID único del servicio', primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(help_text='Nombre del servicio', max_length=100)),
                ('consumo', models.DecimalField(decimal_places=2, help_text='Cantidad consumida', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('unidad', models.CharField(choices=[('m3', 'Metros Cúbicos'), ('kwh', 'Kilovatios/Hora'), ('litros', 'Litros'), ('unidad', 'Unidad'), ('mes', 'Mensual')], help_text='Unidad de medida del consumo', max_length=20)),
                ('tipo', models.CharField(choices=[('agua', 'Agua'), ('luz', 'Electricidad'), ('gas', 'Gas'), ('internet', 'Internet'), ('telefono', 'Teléfono'), ('cable', 'Cable TV'), ('mantenimiento', 'Mantenimiento'), ('limpieza', 'Limpieza'), ('seguridad', 'Seguridad')], help_text='Tipo de servicio', max_length=50)),
                ('fecha_registro', models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Fecha de registro del consumo')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'servicio',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Tiene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Asignación Usuario-Departamento',
                'verbose_name_plural': 'Asignaciones Usuario-Departamento',
                'db_table': 'tiene',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_admin', models.OneToOneField(db_column='id_admin', help_text='ID del administrador (referencia a Persona)', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usuarios.persona')),
                ('nivel_acceso', models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado'), ('super_admin', 'Super Administrador')], default='basico', help_text='Nivel de acceso del administrador', max_length=20)),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'db_table': 'administrador',
            },
        ),
        migrations.CreateModel(
            name='Junta',
            fields=[
                ('id_junta', models.OneToOneField(db_column='id_junta', help_text='ID del miembro de junta (referencia a Persona)', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usuarios.persona')),
                ('cargo', models.CharField(choices=[('presidente', 'Presidente'), ('vicepresidente', 'Vicepresidente'), ('secretario', 'Secretario'), ('tesorero', 'Tesorero'), ('vocal', 'Vocal'), ('sindico', 'Síndico')], help_text='Cargo en la junta directiva', max_length=50)),
            ],
            options={
                'verbose_name': 'Miembro de Junta',
                'verbose_name_plural': 'Junta Directiva',
                'db_table': 'junta',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id_personal', models.OneToOneField(db_column='id_personal', help_text='ID del personal (referencia a Persona)', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usuarios.persona')),
                ('turno', models.CharField(choices=[('mañana', 'Turno Mañana'), ('tarde', 'Turno Tarde'), ('noche', 'Turno Noche'), ('completo', 'Turno Completo')], help_text='Turno de trabajo del personal', max_length=20)),
                ('cargo', models.CharField(choices=[('conserje', 'Conserje'), ('seguridad', 'Seguridad'), ('mantenimiento', 'Mantenimiento'), ('limpieza', 'Limpieza'), ('administracion', 'Administración'), ('supervisor', 'Supervisor')], help_text='Cargo o función del personal', max_length=50)),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
                'db_table': 'personal',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_usuario', models.OneToOneField(db_column='id_usuario', help_text='ID del usuario (referencia a Persona)', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usuarios.persona')),
                ('is_active', models.BooleanField(default=True, help_text='Usuario activo en el sistema')),
                ('is_staff', models.BooleanField(default=False, help_text='Usuario puede acceder al admin')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de registro')),
                ('password', models.CharField(help_text='Hash de la contraseña', max_length=128)),
                ('is_email_verified', models.BooleanField(default=False, help_text='Email verificado')),
                ('email_verification_token', models.CharField(blank=True, help_text='Token de verificación de email', max_length=64, null=True)),
                ('email_verification_expires', models.DateTimeField(blank=True, help_text='Expiración del token de verificación', null=True)),
                ('reset_password_token', models.CharField(blank=True, help_text='Token de recuperación de contraseña', max_length=64, null=True)),
                ('login_token', models.CharField(blank=True, help_text='Token de login temporal', max_length=64, null=True)),
                ('two_factor_secret', models.CharField(blank=True, help_text='Secreto para 2FA', max_length=32, null=True)),
                ('two_factor_enabled', models.BooleanField(default=False, help_text='2FA habilitado')),
                ('failed_login_attempts', models.IntegerField(default=0, help_text='Intentos fallidos de login')),
                ('account_locked_until', models.DateTimeField(blank=True, help_text='Cuenta bloqueada hasta esta fecha', null=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['ci'], name='idx_persona_ci'),
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['email'], name='idx_persona_email'),
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['apellido', 'nombre'], name='idx_persona_nombre_completo'),
        ),
        migrations.AddField(
            model_name='acceso',
            name='id_persona',
            field=models.ForeignKey(help_text='Persona que intentó el acceso', on_delete=django.db.models.deletion.CASCADE, to='usuarios.persona'),
        ),
        migrations.AddField(
            model_name='biometricos',
            name='id_persona',
            field=models.ForeignKey(help_text='Persona asociada a los datos biométricos', on_delete=django.db.models.deletion.CASCADE, to='usuarios.persona'),
        ),
        migrations.AddField(
            model_name='acceso',
            name='id_biometrico',
            field=models.ForeignKey(blank=True, help_text='Datos biométricos utilizados', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.biometricos'),
        ),
        migrations.AddIndex(
            model_name='departamento',
            index=models.Index(fields=['piso'], name='idx_departamento_piso'),
        ),
        migrations.AddIndex(
            model_name='departamento',
            index=models.Index(fields=['nombre_departamento'], name='idx_departamento_nombre'),
        ),
        migrations.AddField(
            model_name='grabacion',
            name='id_camara',
            field=models.ForeignKey(blank=True, help_text='Cámara que realizó la grabación', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.camara'),
        ),
        migrations.AddField(
            model_name='acceso',
            name='id_grabacion',
            field=models.ForeignKey(blank=True, help_text='Grabación asociada al acceso', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.grabacion'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='id_grabacion',
            field=models.ForeignKey(blank=True, help_text='Grabación relacionada con el incidente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.grabacion'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='id_factura',
            field=models.ForeignKey(blank=True, help_text='Factura asociada al mantenimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.factura'),
        ),
        migrations.AddField(
            model_name='factura',
            name='id_pago',
            field=models.OneToOneField(blank=True, help_text='Pago asociado a esta factura', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.pago'),
        ),
        migrations.AddField(
            model_name='realiza',
            name='id_departamento',
            field=models.ForeignKey(help_text='Departamento donde se realiza', on_delete=django.db.models.deletion.CASCADE, to='usuarios.departamento'),
        ),
        migrations.AddField(
            model_name='realiza',
            name='id_mantenimiento',
            field=models.ForeignKey(help_text='Trabajo de mantenimiento', on_delete=django.db.models.deletion.CASCADE, to='usuarios.mantenimiento'),
        ),
        migrations.AddField(
            model_name='reciben',
            name='id_notificacion',
            field=models.ForeignKey(help_text='Notificación recibida', on_delete=django.db.models.deletion.CASCADE, to='usuarios.notificacion'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='id_areacomun',
            field=models.ForeignKey(help_text='Área común reservada', on_delete=django.db.models.deletion.CASCADE, to='usuarios.areacomun'),
        ),
        migrations.AddField(
            model_name='resuelve',
            name='id_incidente',
            field=models.ForeignKey(help_text='Incidente a resolver', on_delete=django.db.models.deletion.CASCADE, to='usuarios.incidente'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='id_departamento',
            field=models.ForeignKey(help_text='Departamento que consume el servicio', on_delete=django.db.models.deletion.CASCADE, to='usuarios.departamento'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='id_factura',
            field=models.ForeignKey(blank=True, help_text='Factura asociada al servicio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.factura'),
        ),
        migrations.AddField(
            model_name='notifican',
            name='id_servicio',
            field=models.ForeignKey(help_text='Servicio sobre el que se notifica', on_delete=django.db.models.deletion.CASCADE, to='usuarios.servicio'),
        ),
        migrations.AddField(
            model_name='tiene',
            name='id_departamento',
            field=models.ForeignKey(help_text='Departamento asignado', on_delete=django.db.models.deletion.CASCADE, to='usuarios.departamento'),
        ),
        migrations.AddField(
            model_name='resuelve',
            name='id_personal',
            field=models.ForeignKey(help_text='Personal asignado', on_delete=django.db.models.deletion.CASCADE, to='usuarios.personal'),
        ),
        migrations.AddField(
            model_name='realiza',
            name='id_personal',
            field=models.ForeignKey(help_text='Personal asignado', on_delete=django.db.models.deletion.CASCADE, to='usuarios.personal'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='id_personal',
            field=models.ForeignKey(blank=True, help_text='Personal que envía la notificación', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.personal'),
        ),
        migrations.AddField(
            model_name='tiene',
            name='id_usuario',
            field=models.ForeignKey(help_text='Usuario propietario/inquilino', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='id_usuario',
            field=models.ForeignKey(help_text='Usuario que hizo la reserva', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='reciben',
            name='id_usuario',
            field=models.ForeignKey(help_text='Usuario receptor', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='pago',
            name='id_usuario',
            field=models.ForeignKey(help_text='Usuario que realizó el pago', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='notifican',
            name='id_usuario',
            field=models.ForeignKey(help_text='Usuario notificado', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='id_usuario',
            field=models.ForeignKey(help_text='Usuario que reporta el incidente', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='auditoriaevento',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario asociado al evento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario'),
        ),
        migrations.AddIndex(
            model_name='grabacion',
            index=models.Index(fields=['-fecha'], name='idx_grabacion_fecha_desc'),
        ),
        migrations.AddIndex(
            model_name='grabacion',
            index=models.Index(fields=['id_camara', '-fecha'], name='idx_grabacion_camara_fecha'),
        ),
        migrations.AddIndex(
            model_name='acceso',
            index=models.Index(fields=['-hora_entrada'], name='idx_acceso_hora_entrada'),
        ),
        migrations.AddIndex(
            model_name='acceso',
            index=models.Index(fields=['id_persona', '-hora_entrada'], name='idx_acceso_persona_fecha'),
        ),
        migrations.AddIndex(
            model_name='acceso',
            index=models.Index(fields=['resultado'], name='idx_acceso_resultado'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['-fecha_emision'], name='idx_factura_fecha_emision'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['estado'], name='idx_factura_estado'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['fecha_vencimiento'], name='idx_factura_vencimiento'),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['-fecha_registro'], name='idx_servicio_fecha'),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['tipo'], name='idx_servicio_tipo'),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['id_departamento', '-fecha_registro'], name='idx_servicio_depto_fecha'),
        ),
        migrations.AlterUniqueTogether(
            name='resuelve',
            unique_together={('id_incidente', 'id_personal')},
        ),
        migrations.AlterUniqueTogether(
            name='realiza',
            unique_together={('id_personal', 'id_mantenimiento', 'id_departamento')},
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['-fecha_envio'], name='idx_notificacion_fecha'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['estado'], name='idx_notificacion_estado'),
        ),
        migrations.AlterUniqueTogether(
            name='tiene',
            unique_together={('id_usuario', 'id_departamento')},
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['fecha', 'hora_inicio'], name='idx_reserva_fecha_hora'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['id_usuario', '-fecha'], name='idx_reserva_usuario_fecha'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['estado'], name='idx_reserva_estado'),
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('id_areacomun', 'fecha', 'hora_inicio', 'hora_fin')},
        ),
        migrations.AlterUniqueTogether(
            name='reciben',
            unique_together={('id_usuario', 'id_notificacion')},
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['-fecha_pago'], name='idx_pago_fecha'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['estado'], name='idx_pago_estado'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['id_usuario', '-fecha_pago'], name='idx_pago_usuario_fecha'),
        ),
        migrations.AlterUniqueTogether(
            name='notifican',
            unique_together={('id_usuario', 'id_servicio', 'fecha_envio')},
        ),
        migrations.AddIndex(
            model_name='incidente',
            index=models.Index(fields=['-fecha'], name='idx_incidente_fecha'),
        ),
        migrations.AddIndex(
            model_name='incidente',
            index=models.Index(fields=['tipo'], name='idx_incidente_tipo'),
        ),
        migrations.AddIndex(
            model_name='incidente',
            index=models.Index(fields=['id_usuario', '-fecha'], name='idx_incidente_usuario_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaevento',
            index=models.Index(fields=['-fecha'], name='idx_auditoria_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaevento',
            index=models.Index(fields=['evento'], name='idx_auditoria_evento'),
        ),
        migrations.AddIndex(
            model_name='auditoriaevento',
            index=models.Index(fields=['usuario', '-fecha'], name='idx_auditoria_usuario_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaevento',
            index=models.Index(fields=['username'], name='idx_auditoria_username'),
        ),
    ]
