# Generated by Django 5.2.6 on 2025-09-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_rol_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email_verification_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
