# Generated by Django 5.2.6 on 2025-09-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_password_usuario_password_encrypted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='reset_password_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
