# Generated by Django 5.2.6 on 2025-09-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='login_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
