# Generated by Django 5.2.6 on 2025-09-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_add_email_verification_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriaevento',
            name='evento',
            field=models.CharField(choices=[('login_exitoso', 'Login exitoso'), ('login_fallido', 'Login fallido'), ('logout_exitoso', 'Logout exitoso'), ('cambio_password', 'Cambio de contraseña'), ('reset_password', 'Reset de contraseña'), ('acceso_no_autorizado', 'Acceso no autorizado')], max_length=32),
        ),
    ]
