# Generated by Django 5.2.6 on 2025-10-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_activo_usuario_apartamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='reset_password_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
