# Generated by Django 5.2.7 on 2025-10-21 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_must_change_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriaevento',
            name='evento',
            field=models.CharField(choices=[('login_exitoso', 'Login exitoso'), ('login_fallido', 'Login fallido'), ('logout_exitoso', 'Logout exitoso'), ('cambio_password', 'Cambio de contraseña'), ('reset_password', 'Reset de contraseña'), ('acceso_no_autorizado', 'Acceso no autorizado'), ('invoice_created', 'Invoice creado'), ('payment_manual', 'Pago manual registrado'), ('payroll_approved', 'Nómina aprobada'), ('payroll_executed', 'Nómina ejecutada'), ('overdue_charge_applied', 'Cargo por morosidad aplicado')], max_length=32),
        ),
    ]
