# Generated by Django 5.2.6 on 2025-09-16 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_groups_usuario_is_superuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='id_usuario',
            new_name='id',
        ),
    ]
