# Generated by Django 5.2.6 on 2025-09-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_usuario_two_factor_enabled_usuario_two_factor_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='account_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
