"""
Django settings for edificiobackend project.

Sistema de gestión de edificios con autenticación JWT, auditoría y seguridad avanzada.
Configuración optimizada para desarrollo y producción.

Generated by Django 5.2.6
Optimizado: 4 de octubre de 2025
"""

# ============================================================================
# IMPORTS
# ============================================================================

# Imports estándar de Python
import base64
import os
from datetime import timedelta
from pathlib import Path

# Imports de Django
from django.core.management.utils import get_random_secret_key

# ============================================================================
# CONFIGURACIÓN BASE DEL PROYECTO
# ============================================================================

# Ruta base del proyecto
BASE_DIR = Path(__file__).resolve().parent.parent

# ============================================================================
# VARIABLES DE ENTORNO Y CONFIGURACIÓN DE SEGURIDAD
# ============================================================================

def get_env_variable(var_name: str, default_value: str = None, required: bool = False) -> str:
    """
    Obtener variable de entorno con validación y valores por defecto
    """
    value = os.environ.get(var_name, default_value)
    if required and not value:
        raise EnvironmentError(f"Variable de entorno requerida no encontrada: {var_name}")
    return value

def get_bool_env(var_name: str, default_value: bool = False) -> bool:
    """
    Convertir variable de entorno a booleano
    """
    value = get_env_variable(var_name, str(default_value))
    return value.lower() in ('true', '1', 'yes', 'on')

# Configuraciones de entorno
ENVIRONMENT = get_env_variable('DJANGO_ENVIRONMENT', 'development')
DEBUG = get_bool_env('DEBUG', default_value=ENVIRONMENT == 'development')

# Secret key con generación automática para desarrollo
SECRET_KEY = get_env_variable(
    'SECRET_KEY', 
    'django-insecure-sb-&l2*xlxbr3ta&*)_3i3y3!=(26hp7%z=xa-%^hcc*#5d2pe' if DEBUG else None,
    required=not DEBUG
)

# Hosts permitidos
ALLOWED_HOSTS = get_env_variable('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if not DEBUG else ['*']


# ============================================================================
# APLICACIONES INSTALADAS
# ============================================================================

# Aplicaciones base de Django
DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# Aplicaciones de terceros
THIRD_PARTY_APPS = [
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
]

# Aplicaciones locales del proyecto
LOCAL_APPS = [
    'apps.usuarios',
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

# ============================================================================
# MIDDLEWARE
# ============================================================================

MIDDLEWARE = [
    # Seguridad y CORS - Orden importante
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    
    # Sesiones y contenido
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    
    # CSRF y autenticación
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    
    # Protección contra clickjacking
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'edificiobackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'edificiobackend.wsgi.application'


# ============================================================================
# CONFIGURACIÓN DE BASE DE DATOS
# ============================================================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': get_env_variable('DB_NAME', 'bdedificio'),
        'USER': get_env_variable('DB_USER', 'postgres'),
        'PASSWORD': get_env_variable('DB_PASSWORD', '12345'),
        'HOST': get_env_variable('DB_HOST', 'localhost'),
        'PORT': get_env_variable('DB_PORT', '5432'),
        
        # Optimizaciones de conexión
        'OPTIONS': {
            'connect_timeout': 60,
            'options': '-c default_transaction_isolation=serializable'
        },
        
        # Pool de conexiones para producción
        'CONN_MAX_AGE': 600 if not DEBUG else 0,  # 10 minutos en producción
        'CONN_HEALTH_CHECKS': True,
        
        # Configuraciones adicionales de rendimiento
        'TEST': {
            'NAME': 'test_bdedificio',
        }
    }
}

# Configuración adicional para PostgreSQL
if not DEBUG:
    DATABASES['default']['OPTIONS'].update({
        'MAX_CONNS': 20,
        'connect_timeout': 60,
    })


# ============================================================================
# VALIDADORES DE CONTRASEÑA
# ============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        'OPTIONS': {
            'user_attributes': ('username', 'email', 'first_name', 'last_name'),
            'max_similarity': 0.7,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': int(get_env_variable('PASSWORD_MIN_LENGTH', '8')),
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Configuración adicional para hasheo de contraseñas
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',      # Más seguro (recomendado)
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',      # Por defecto Django
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',  # Compatibilidad
    'django.contrib.auth.hashers.ScryptPasswordHasher',      # Alternativa moderna
]


# ============================================================================
# INTERNACIONALIZACIÓN Y LOCALIZACIÓN
# ============================================================================

LANGUAGE_CODE = get_env_variable('LANGUAGE_CODE', 'es-bo')  # Español de Bolivia
TIME_ZONE = get_env_variable('TIME_ZONE', 'America/La_Paz')

USE_I18N = True
USE_L10N = True
USE_TZ = True

# Idiomas disponibles
LANGUAGES = [
    ('es', 'Español'),
    ('en', 'English'),
]

# Configuración de formato de fecha
DATE_FORMAT = 'd/m/Y'
DATETIME_FORMAT = 'd/m/Y H:i:s'
SHORT_DATE_FORMAT = 'd/m/Y'

# ============================================================================
# ARCHIVOS ESTÁTICOS Y MEDIA
# ============================================================================

# URLs
STATIC_URL = '/static/'
MEDIA_URL = '/media/'

# Directorios
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_ROOT = BASE_DIR / 'media'

# Directorios adicionales para archivos estáticos en desarrollo
STATICFILES_DIRS = []
if DEBUG:
    static_dir = BASE_DIR / 'static'
    if static_dir.exists():
        STATICFILES_DIRS.append(static_dir)

# Finders para archivos estáticos
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# ============================================================================
# CONFIGURACIONES ESPECÍFICAS POR ENTORNO
# ============================================================================

# Configuraciones de desarrollo
if DEBUG:
    # Toolbar de debug (opcional)
    if get_bool_env('USE_DEBUG_TOOLBAR', False):
        INSTALLED_APPS += ['debug_toolbar']
        MIDDLEWARE += ['debug_toolbar.middleware.DebugToolbarMiddleware']
        INTERNAL_IPS = ['127.0.0.1', '::1']
    
    # Configuraciones relajadas para desarrollo
    ALLOWED_HOSTS = ['*']
    
# Configuraciones de producción
else:
    # Optimizaciones para producción
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True
    USE_X_FORWARDED_PORT = True
    
    # Compresión de archivos estáticos
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'

# ============================================================================
# CONFIGURACIONES FINALES
# ============================================================================

# Tipo de campo de clave primaria por defecto
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Modelo de usuario personalizado (temporalmente comentado para migraciones)
AUTH_USER_MODEL = 'usuarios.Usuario'

# ============================================================================
# CONFIGURACIONES DE RENDIMIENTO Y OPTIMIZACIÓN
# ============================================================================

# Configuración de sesiones optimizada
SESSION_SAVE_EVERY_REQUEST = False
SESSION_COOKIE_NAME = 'edificio_sessionid'

# Configuración de archivos de datos (para uploads)
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880   # 5MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000

# Configuración de timeouts
DEFAULT_TIMEOUT = 30

# ============================================================================
# DOCUMENTACIÓN Y NOTAS FINALES
# ============================================================================

"""
CONFIGURACIONES IMPLEMENTADAS:

1. SEGURIDAD MEJORADA:
   - Variables de entorno para credenciales sensibles
   - Configuraciones HTTPS y HSTS para producción
   - Headers de seguridad avanzados (CSP, XSS, etc.)
   - Cookies seguras con HttpOnly y SameSite
   - Validadores de contraseña robustos con Argon2

2. RENDIMIENTO OPTIMIZADO:
   - Pool de conexiones de base de datos
   - Sistema de cache con Redis en producción
   - Compresión de archivos estáticos
   - Throttling de API para prevenir abuso
   - Logging con rotación de archivos

3. CONFIGURACIONES POR ENTORNO:
   - Variables de entorno para todas las configuraciones sensibles
   - Configuraciones específicas para desarrollo/producción
   - Debug toolbar opcional para desarrollo
   - Diferentes backends para email y cache según entorno

4. API REST FRAMEWORK:
   - Paginación configurada
   - Filtros y búsqueda habilitados
   - Throttling para prevenir abuso
   - Autenticación JWT optimizada

5. INTERNACIONALIZACIÓN:
   - Configurado para español de Bolivia
   - Formatos de fecha localizados
   - Soporte multi-idioma preparado

6. LOGGING ESTRUCTURADO:
   - Diferentes niveles por aplicación
   - Rotación automática de logs
   - Logs de seguridad separados
   - Notificaciones por email para errores críticos

VARIABLES DE ENTORNO REQUERIDAS PARA PRODUCCIÓN:
- SECRET_KEY: Clave secreta única y compleja
- DB_NAME, DB_USER, DB_PASSWORD, DB_HOST: Configuración de PostgreSQL
- EMAIL_HOST_USER, EMAIL_HOST_PASSWORD: Configuración SMTP
- AES_KEY_B64: Clave AES para encriptación de datos biométricos
- ALLOWED_HOSTS: Hosts permitidos separados por comas
- CORS_ALLOWED_ORIGINS: Orígenes CORS permitidos
- REDIS_URL: URL de conexión a Redis para cache

PRÓXIMOS PASOS RECOMENDADOS:
- Configurar Redis para cache en producción
- Implementar monitoreo con Sentry
- Configurar backup automático de base de datos
- Implementar health checks para contenedores
"""


# ============================================================================
# CONFIGURACIÓN DE LOGGING
# ============================================================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'json': {
            'format': '{"level": "%(levelname)s", "time": "%(asctime)s", "module": "%(module)s", "message": "%(message)s"}',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'maxBytes': 15728640,  # 15MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'security.log',
            'maxBytes': 15728640,  # 15MB
            'backupCount': 10,
            'formatter': 'json',
        },
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
            'formatter': 'verbose',
        }
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file', 'mail_admins'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['security_file', 'mail_admins'],
            'level': 'WARNING',
            'propagate': False,
        },
        'apps.usuarios': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}

# Crear directorio de logs si no existe
os.makedirs(BASE_DIR / 'logs', exist_ok=True)

# ============================================================================
# CONFIGURACIÓN DE CACHE
# ============================================================================

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache' if not DEBUG else 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': get_env_variable('REDIS_URL', 'redis://127.0.0.1:6379/1') if not DEBUG else 'unique-snowflake',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        } if not DEBUG else {},
        'KEY_PREFIX': 'edificio_backend',
        'TIMEOUT': 300,  # 5 minutos por defecto
        'VERSION': 1,
    }
}

# Session storage usando cache en producción
if not DEBUG:
    SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
    SESSION_CACHE_ALIAS = 'default'

# ============================================================================
# CONFIGURACIÓN DE ENCRIPTACIÓN AES
# ============================================================================

# ============================================================================
# CONFIGURACIÓN DE ENCRIPTACIÓN AES
# ============================================================================

def generate_aes_key() -> str:
    """Generar una clave AES-256 válida en base64"""
    import secrets
    key_bytes = secrets.token_bytes(32)  # 32 bytes = 256 bits
    return base64.b64encode(key_bytes).decode()

def get_or_create_aes_key() -> bytes:
    """Obtener o crear clave AES válida"""
    # Clave por defecto válida para desarrollo (32 bytes)
    default_key = "MTIzNDU2Nzg5MDEyMzQ1NjEyMzQ1Njc4OTAxMjM0NTY="  # "123456789012345612345678901234567" en base64
    
    AES_KEY_B64 = get_env_variable("AES_KEY_B64", default_key)
    
    try:
        key_bytes = base64.b64decode(AES_KEY_B64)
        if len(key_bytes) != 32:
            if DEBUG:
                # En desarrollo, generar clave válida automáticamente
                print(f"⚠️  Clave AES inválida ({len(key_bytes)} bytes). Generando clave válida...")
                new_key = generate_aes_key()
                print(f"💡 Nueva clave AES generada: {new_key}")
                print(f"💡 Agrega esta variable a tu .env: AES_KEY_B64={new_key}")
                return base64.b64decode(new_key)
            else:
                raise ValueError(f"AES key debe ser de 32 bytes, recibido: {len(key_bytes)} bytes")
        
        return key_bytes
        
    except Exception as e:
        if DEBUG:
            print(f"⚠️  Error decodificando AES key: {e}")
            print("💡 Usando clave por defecto para desarrollo...")
            return base64.b64decode(default_key)
        else:
            raise EnvironmentError(f"Error decodificando AES_KEY_B64: {e}")

# Obtener clave AES
AES_KEY = get_or_create_aes_key()

# ============================================================================
# CONFIGURACIÓN DE DJANGO REST FRAMEWORK
# ============================================================================

REST_FRAMEWORK = {
    # Autenticación
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',  # Para admin panel
    ],
    
    # Permisos por defecto
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    
    # Filtros
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    
    # Paginación
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    
    # Renderizadores
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer' if DEBUG else 'rest_framework.renderers.JSONRenderer',
    ],
    
    # Parser classes
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    
    # Throttling para prevenir abuso de API
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
        'login': '5/min',  # Límite específico para login
    }
}

# ============================================================================
# CONFIGURACIÓN DE CORS
# ============================================================================

# En desarrollo permitir todos los orígenes, en producción ser específico
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [
        origin.strip() for origin in get_env_variable('CORS_ALLOWED_ORIGINS', 'http://localhost:4200').split(',')
    ]

# Headers permitidos
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Métodos HTTP permitidos
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Configuración de cookies en CORS
CORS_ALLOW_CREDENTIALS = True

# ============================================================================
# CONFIGURACIÓN DE EMAIL
# ============================================================================

# Backend de email según el entorno
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Configuraciones SMTP para producción
EMAIL_HOST = get_env_variable('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(get_env_variable('EMAIL_PORT', '587'))
EMAIL_HOST_USER = get_env_variable('EMAIL_HOST_USER', 'innovabuilding01@gmail.com')
EMAIL_HOST_PASSWORD = get_env_variable('EMAIL_HOST_PASSWORD', 'tlfv jnlw fyax llmu')
EMAIL_USE_TLS = get_bool_env('EMAIL_USE_TLS', True)
EMAIL_USE_SSL = get_bool_env('EMAIL_USE_SSL', False)

# Configuraciones adicionales
DEFAULT_FROM_EMAIL = get_env_variable('DEFAULT_FROM_EMAIL', 'noreply@edificioapp.com')
SERVER_EMAIL = get_env_variable('SERVER_EMAIL', DEFAULT_FROM_EMAIL)

# Timeout para conexiones SMTP
EMAIL_TIMEOUT = 30

# Lista de administradores para notificaciones críticas
ADMINS = [
    ('Admin', get_env_variable('ADMIN_EMAIL', 'admin@edificioapp.com')),
]
MANAGERS = ADMINS

# ============================================================================
# CONFIGURACIÓN DE JWT (JSON Web Tokens)
# ============================================================================

SIMPLE_JWT = {
    # Tiempos de vida de los tokens
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(get_env_variable('JWT_ACCESS_TOKEN_MINUTES', '15'))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(get_env_variable('JWT_REFRESH_TOKEN_DAYS', '7'))),
    
    # Rotación y blacklist de tokens
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    
    # Algoritmo de firma
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    
    # Headers
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    
    # Claims adicionales
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    
    # Configuraciones de sliding tokens (opcional)
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# ============================================================================
# CONFIGURACIONES DE SEGURIDAD AVANZADAS
# ============================================================================

# Configuraciones de seguridad HTTP
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Configuraciones SSL/HTTPS (activar en producción)
if not DEBUG:
    SECURE_SSL_REDIRECT = get_bool_env('SECURE_SSL_REDIRECT', True)
    SECURE_HSTS_SECONDS = int(get_env_variable('SECURE_HSTS_SECONDS', '31536000'))  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Configuraciones de cookies
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_TRUSTED_ORIGINS = [
    origin.strip() for origin in get_env_variable('CSRF_TRUSTED_ORIGINS', 'http://localhost:4200').split(',')
]

SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_AGE = 3600  # 1 hora
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Content Security Policy (CSP)
if not DEBUG:
    CSP_DEFAULT_SRC = ("'self'",)
    CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'")
    CSP_STYLE_SRC = ("'self'", "'unsafe-inline'")
    CSP_IMG_SRC = ("'self'", "data:", "https:")
    CSP_FONT_SRC = ("'self'", "https:")
    CSP_CONNECT_SRC = ("'self'",)

# Django usa esto por defecto para hashear contraseñas
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',     # PBKDF2-SHA256
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher', # PBKDF2-SHA1  
    'django.contrib.auth.hashers.ScryptPasswordHasher',     # Scrypt
]